name: Cleanup Dev

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-ui-pr-preview:
    permissions:
      contents: read
      id-token: 'write'
      issues: write
    runs-on: ubuntu-latest

    steps:
      - name: Create an empty directory for cleanup
        run: mkdir -p empty

      - name: Remove GitHub Pages Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./empty
          destination_dir: ui/pr/${{ github.event.pull_request.number }}
          keep_files: false
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          publish_branch: gh-pages
          commit_message: 'chore: Clean up preview for PR #${{ github.event.pull_request.number }}'

      - name: Log Cleanup Completion
        run: echo "Cleanup completed for PR \#${{ github.event.pull_request.number }}"

  update-preview-comment:
    name: Update PR Comment
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Update PR comment to reflect cleanup
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            <!-- pr-preview-comment -->
            🧹 The live preview for this PR has been removed.
