name: Main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-check:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run quality and typing checks
        run: make quality
        working-directory: ui

  precommit-check:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run pre-commit checks
        run: npx husky run pre-commit
        working-directory: ui

  unit-tests:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run unit tests
        run: make test-unit
        working-directory: ui

  integration-tests:
    permissions:
      contents: "read"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Run integration tests
        run: make test-integration
        working-directory: ui

  publish-gh-pages:
    needs: [quality-check, precommit-check, unit-tests, integration-tests]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ui

      - name: Build app to root
        id: build
        run: |
          # Export vars to ensure they are loaded before build
          export $(grep -v '^#' .env.development | xargs)

          # Set asset prefix and base path with PR number
          ASSET_PREFIX=https://neuralmagic.github.io/guidellm/ui/dev
          BASE_PATH=/ui/dev
          GIT_SHA=${{ github.sha }}
          export ASSET_PREFIX=${ASSET_PREFIX}
          export BASE_PATH=${BASE_PATH}
          export GIT_SHA=${GIT_SHA}
          npm run build
        working-directory: ui

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/out
          destination_dir: ui/dev
          keep_files: false
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          publish_branch: gh-pages
